export const navItems = [
  { href: "/", label: "Home", current: "Overview" },
  { href: "/age-guide", label: "年代別", current: "Age Pairing" },
  { href: "/cuts", label: "部位一覧", current: "Cuts Library" },
  { href: "/grill-guide", label: "焼き方", current: "Grilling Method" },
  { href: "/share-grill", label: "共有", current: "Shared Grill Notes" },
  { href: "/#diagnosis", label: "診断", current: "Taste Finder" },
];

export const pageCards = [
  {
    href: "/age-guide",
    eyebrow: "Age Pairing",
    title: "年代別おすすめ",
    description:
      "10代から50代以上まで、脂の甘み・赤身の旨味・食後の軽さを軸に、年代ごとに合う部位を提案します。",
    points: ["おすすめ部位", "味の方向性", "焼き方と食べ方"],
    image: "/images/cuts/karubi.png",
  },
  {
    href: "/cuts",
    eyebrow: "Cuts Library",
    title: "部位一覧",
    description:
      "牛タン、カルビ、ロース、希少部位、ホルモンまで。脂の強さや食べ応えで選べる部位カード集です。",
    points: ["カテゴリ絞り込み", "5段階メーター", "おすすめ年代"],
    image: "/images/cuts/rosu.png",
  },
  {
    href: "/grill-guide",
    eyebrow: "Grilling Method",
    title: "焼き方ガイド",
    description:
      "タン、カルビ、赤身、ヒレ、ホルモン。部位タイプごとに火加減と焼き上げの考え方を整理します。",
    points: ["火加減", "焼き時間の考え方", "失敗しにくいコツ"],
    image: "/images/cuts/gyutan.png",
  },
  {
    href: "/share-grill",
    eyebrow: "Shared Grill Notes",
    title: "みんなの焼き方共有",
    description:
      "投稿カードで焼き方をシェア。ランダム選択で、今夜試したい一枚にも出会えます。",
    points: ["投稿フォーム", "ランダム選択", "部位タイプ別フィルター"],
    image: "/images/cuts/harami.png",
  },
];

export const ageGuides = [
  {
    age: "10代",
    theme: "まずは焼肉の楽しさを知る、王道部位",
    catch: "香ばしさ、脂の甘み、食べ応え。焼肉らしい歓声が上がる一皿から。",
    cuts: ["カルビ", "ハラミ", "タン", "ロース"],
    why:
      "脂の甘みや食べ応えを感じやすく、焼肉の満足感がわかりやすい部位を中心に。友人同士の食事や食べ放題でも選びやすく、焼く時間も短いので会話のテンポを止めません。",
    taste: "甘い脂、香ばしい焼き目、濃いめのタレが映える味わい。",
    grill: "強火で表面を香ばしく。カルビは脂が落ちるので網の端に避けながら焼く。",
    pairing: "甘辛だれ、白ごはん、レモンを添えたタン塩。",
    image: "/images/cuts/karubi.png",
  },
  {
    age: "20代",
    theme: "量も味も楽しみたい、バランス重視",
    catch: "脂、赤身、ホルモンまで。好みの幅が一気に広がる年代へ。",
    cuts: ["上カルビ", "ハラミ", "中落ちカルビ", "タン塩", "ホルモン"],
    why:
      "脂の旨味、赤身の食べ応え、ホルモンの個性を広く楽しめる年代。焼肉の好みが広がり始める時期だからこそ、王道と少しクセのある部位を組み合わせると満足度が上がります。",
    taste: "ジューシーな脂と赤身の旨味、ホルモンの甘い余韻。",
    grill: "脂の多い部位は焦がしすぎず、ホルモンは皮目からじっくり。",
    pairing: "塩だれ、辛味噌、冷えたビールや烏龍茶。",
    image: "/images/cuts/harami.png",
  },
  {
    age: "30代",
    theme: "脂だけではなく、肉の旨味を選ぶ",
    catch: "一枚ごとの香りと余韻を楽しむ、焼肉の解像度が上がる選び方。",
    cuts: ["ロース", "ハラミ", "ランプ", "イチボ", "上タン"],
    why:
      "脂の量よりも、肉質・香り・旨味のバランスを重視したい年代。希少部位や赤身の魅力を知り始め、焼き加減や薬味によって味が変わる楽しさも感じやすくなります。",
    taste: "赤身の旨味、ほどよい脂、鼻に抜ける香ばしさ。",
    grill: "赤身は焼きすぎず、中心に少し赤みを残して休ませる。",
    pairing: "塩、わさび、山椒、軽めの赤ワイン。",
    image: "/images/cuts/rosu.png",
  },
  {
    age: "40代",
    theme: "上質な赤身とほどよい脂を味わう",
    catch: "少量でも深い満足感。柔らかさと余韻で選ぶ大人の焼肉。",
    cuts: ["ヒレ", "ランプ", "イチボ", "サーロイン", "ミノ"],
    why:
      "重すぎない脂、柔らかさ、肉の余韻を大切にしたい年代。量より質を意識し、数枚でも満足できる上質な部位を丁寧に焼くことで食後の心地よさが変わります。",
    taste: "澄んだ赤身、上品な脂、噛むほどに伸びる旨味。",
    grill: "ヒレやランプは火を入れすぎず、サーロインは脂を落としながら短時間で。",
    pairing: "塩、わさび、ポン酢、香りのよい日本酒。",
    image: "/images/cuts/hire.png",
  },
  {
    age: "50代以上",
    theme: "軽やかに、深く味わう大人の焼肉",
    catch: "脂の強さより、噛むほどに広がる旨味と食後の軽さを。",
    cuts: ["ヒレ", "赤身ロース", "上タン", "ミノ", "テール系メニュー"],
    why:
      "脂の強さよりも、噛むほどに広がる旨味、消化のしやすさ、食後の軽さを重視。焼きすぎず、塩やわさびで輪郭を整えると、部位そのものの品のよさが際立ちます。",
    taste: "軽やかな赤身、歯切れのよさ、静かな旨味の余韻。",
    grill: "弱めの火で丁寧に。タンやミノは香ばしさを出し、赤身は焼きすぎない。",
    pairing: "塩、レモン、わさび、出汁の効いたスープ。",
    image: "/images/cuts/gyutan.png",
  },
];

export const filterCategories = [
  "すべて",
  "脂を楽しむ",
  "赤身を楽しむ",
  "さっぱり",
  "希少部位",
  "ホルモン系",
];

export const cuts = [
  {
    name: "牛タン",
    category: "さっぱり",
    description: "歯切れのよさと香ばしさが魅力。焼肉の始まりに最適な一皿。",
    fat: 2,
    texture: 4,
    age: "20代〜50代以上",
    doneness: "強火で短時間",
    pairing: "塩、レモン、ねぎ",
    image: "/images/cuts/gyutan.png",
  },
  {
    name: "カルビ",
    category: "脂を楽しむ",
    description: "焼肉らしい甘い脂と濃厚な旨味。ごはんとの相性が抜群。",
    fat: 5,
    texture: 4,
    age: "10代〜30代",
    doneness: "表面を香ばしく",
    pairing: "甘辛だれ、白ごはん",
    image: "/images/cuts/karubi.png",
  },
  {
    name: "上カルビ",
    category: "脂を楽しむ",
    description: "きめ細かなサシが溶ける贅沢なカルビ。少量でも満足感が高い。",
    fat: 5,
    texture: 4,
    age: "20代〜40代",
    doneness: "強火でさっと",
    pairing: "わさび、塩だれ",
    image: "/images/cuts/karubi.png",
  },
  {
    name: "中落ちカルビ",
    category: "脂を楽しむ",
    description: "骨まわりの濃い旨味とジューシーな脂が楽しめる力強い部位。",
    fat: 5,
    texture: 5,
    age: "10代〜30代",
    doneness: "脂を落としながら",
    pairing: "辛味噌、にんにく醤油",
    image: "/images/cuts/karubi.png",
  },
  {
    name: "ロース",
    category: "赤身を楽しむ",
    description: "脂と赤身のバランスがよく、肉の旨味を素直に味わえる定番。",
    fat: 3,
    texture: 3,
    age: "10代〜50代以上",
    doneness: "中火で焼きすぎない",
    pairing: "たれ、塩、わさび",
    image: "/images/cuts/rosu.png",
  },
  {
    name: "上ロース",
    category: "赤身を楽しむ",
    description: "柔らかく上品な脂を含むロース。大人の焼肉にもよく合う。",
    fat: 3,
    texture: 3,
    age: "30代〜50代以上",
    doneness: "ミディアム寄り",
    pairing: "塩、山椒、ポン酢",
    image: "/images/cuts/rosu.png",
  },
  {
    name: "ハラミ",
    category: "赤身を楽しむ",
    description: "赤身のような食べ応えと肉汁の濃さが魅力。幅広い年代に人気。",
    fat: 3,
    texture: 5,
    age: "10代〜40代",
    doneness: "表面をしっかり",
    pairing: "たれ、にんにく、黒胡椒",
    image: "/images/cuts/harami.png",
  },
  {
    name: "サガリ",
    category: "赤身を楽しむ",
    description: "ハラミより軽やかで、やわらかな繊維感と澄んだ旨味がある。",
    fat: 2,
    texture: 4,
    age: "20代〜50代以上",
    doneness: "中火で短め",
    pairing: "塩、レモン、柚子胡椒",
    image: "/images/cuts/harami.png",
  },
  {
    name: "ヒレ",
    category: "さっぱり",
    description: "非常に柔らかく脂が控えめ。上質な赤身を静かに味わえる。",
    fat: 1,
    texture: 2,
    age: "30代〜50代以上",
    doneness: "弱めの火で丁寧に",
    pairing: "塩、わさび、赤ワイン",
    image: "/images/cuts/hire.png",
  },
  {
    name: "サーロイン",
    category: "脂を楽しむ",
    description: "華やかな脂と柔らかさが主役。特別感のある一枚に向く。",
    fat: 5,
    texture: 3,
    age: "30代〜40代",
    doneness: "片面を強く短時間",
    pairing: "塩、わさび、すき焼き風",
    image: "/images/cuts/sirloin.png",
  },
  {
    name: "ランプ",
    category: "赤身を楽しむ",
    description: "赤身の旨味が濃く、脂は控えめ。肉好きに刺さる端正な味。",
    fat: 2,
    texture: 3,
    age: "30代〜50代以上",
    doneness: "中心に赤みを残す",
    pairing: "塩、わさび、山椒",
    image: "/images/cuts/harami.png",
  },
  {
    name: "イチボ",
    category: "希少部位",
    description: "赤身の旨味と霜降りの甘さが同居する、奥行きのある希少部位。",
    fat: 3,
    texture: 3,
    age: "30代〜50代以上",
    doneness: "中火でさっと",
    pairing: "塩、わさび、柚子胡椒",
    image: "/images/cuts/harami.png",
  },
  {
    name: "ミスジ",
    category: "希少部位",
    description: "繊細なサシととろける食感。脂の質を上品に楽しめる。",
    fat: 4,
    texture: 2,
    age: "20代〜40代",
    doneness: "強火で片面を短く",
    pairing: "塩、わさび、卵黄だれ",
    image: "/images/cuts/harami.png",
  },
  {
    name: "ザブトン",
    category: "希少部位",
    description: "濃厚な霜降りと柔らかさが際立つ、贅沢感のある肩ロース系。",
    fat: 5,
    texture: 2,
    age: "20代〜40代",
    doneness: "炙るように短時間",
    pairing: "塩、すき焼きだれ",
    image: "/images/cuts/karubi.png",
  },
  {
    name: "カイノミ",
    category: "希少部位",
    description: "カルビの旨味とヒレの柔らかさを併せ持つ、軽やかな希少部位。",
    fat: 3,
    texture: 3,
    age: "20代〜40代",
    doneness: "中火でふっくら",
    pairing: "塩、たれ、わさび",
    image: "/images/cuts/karubi.png",
  },
  {
    name: "トモサンカク",
    category: "希少部位",
    description: "赤身の濃さにきれいなサシが入る、香り高いモモ系の一枚。",
    fat: 3,
    texture: 3,
    age: "30代〜50代以上",
    doneness: "焼きすぎず中火",
    pairing: "塩、山椒、ポン酢",
    image: "/images/cuts/harami.png",
  },
  {
    name: "シンシン",
    category: "希少部位",
    description: "きめ細かな赤身でクセが少なく、柔らかな口当たりが続く。",
    fat: 2,
    texture: 2,
    age: "30代〜50代以上",
    doneness: "弱めの中火",
    pairing: "塩、わさび、レモン",
    image: "/images/cuts/harami.png",
  },
  {
    name: "ウチモモ",
    category: "さっぱり",
    description: "脂が少なく、すっきりした赤身の味。軽く食べたい日に向く。",
    fat: 1,
    texture: 3,
    age: "40代〜50代以上",
    doneness: "焼きすぎない",
    pairing: "塩、ポン酢、大根おろし",
    image: "/images/cuts/harami.png",
  },
  {
    name: "リブロース",
    category: "脂を楽しむ",
    description: "肉の香り、脂の甘み、柔らかさが揃う華やかなロース。",
    fat: 4,
    texture: 3,
    age: "20代〜40代",
    doneness: "強火で香ばしく",
    pairing: "たれ、塩、わさび",
    image: "/images/cuts/rosu.png",
  },
  {
    name: "ホルモン",
    category: "ホルモン系",
    description: "脂の甘みと弾む食感が楽しい。香ばしく焼くほど旨味が増す。",
    fat: 4,
    texture: 5,
    age: "20代〜40代",
    doneness: "皮目からじっくり",
    pairing: "味噌だれ、七味、ビール",
    image: "/images/cuts/horumon.png",
  },
  {
    name: "シマチョウ",
    category: "ホルモン系",
    description: "ぷるっとした脂と縞状の食感。焼き上げると甘い香りが立つ。",
    fat: 5,
    texture: 5,
    age: "20代〜40代",
    doneness: "脂を落としながら",
    pairing: "辛味噌、にんにく",
    image: "/images/cuts/horumon.png",
  },
  {
    name: "マルチョウ",
    category: "ホルモン系",
    description: "丸い形に包まれた濃厚な脂が特徴。少量で強い満足感。",
    fat: 5,
    texture: 4,
    age: "20代〜30代",
    doneness: "弱火からじっくり",
    pairing: "味噌だれ、柚子胡椒",
    image: "/images/cuts/horumon.png",
  },
  {
    name: "ミノ",
    category: "ホルモン系",
    description: "脂は控えめで、さくっとした歯切れが魅力。大人にも好まれる。",
    fat: 2,
    texture: 5,
    age: "30代〜50代以上",
    doneness: "表面を香ばしく",
    pairing: "塩、レモン、味噌だれ",
    image: "/images/cuts/mino.png",
  },
  {
    name: "ハチノス",
    category: "ホルモン系",
    description: "淡白ながら独特の食感があり、噛むほどに旨味が出る胃袋部位。",
    fat: 1,
    texture: 4,
    age: "30代〜50代以上",
    doneness: "中火でじっくり",
    pairing: "酢味噌、辛味噌",
    image: "/images/cuts/mino.png",
  },
  {
    name: "レバー",
    category: "ホルモン系",
    description: "濃い旨味としっとりした質感。火入れで印象が大きく変わる。",
    fat: 1,
    texture: 3,
    age: "20代〜50代以上",
    doneness: "中心まで丁寧に",
    pairing: "ごま油塩、にんにく醤油",
    image: "/images/cuts/horumon.png",
  },
  {
    name: "ハツ",
    category: "さっぱり",
    description: "歯切れがよく、後味が軽い。塩で食べると香りが澄む。",
    fat: 1,
    texture: 4,
    age: "20代〜50代以上",
    doneness: "強火で短時間",
    pairing: "塩、レモン、黒胡椒",
    image: "/images/cuts/horumon.png",
  },
  {
    name: "センマイ",
    category: "ホルモン系",
    description: "しゃきっとした食感と軽さが特徴。箸休めにもなる個性派。",
    fat: 1,
    texture: 4,
    age: "30代〜50代以上",
    doneness: "さっと温める程度",
    pairing: "酢味噌、辛味噌",
    image: "/images/cuts/mino.png",
  },
  {
    name: "ギアラ",
    category: "ホルモン系",
    description: "濃厚な旨味と弾力があり、香ばしく焼くと奥深い甘みが出る。",
    fat: 3,
    texture: 5,
    age: "20代〜40代",
    doneness: "じっくり香ばしく",
    pairing: "味噌だれ、山椒",
    image: "/images/cuts/mino.png",
  },
  {
    name: "テール",
    category: "さっぱり",
    description: "焼き物だけでなくスープにも映える、滋味深く軽やかな旨味。",
    fat: 2,
    texture: 4,
    age: "40代〜50代以上",
    doneness: "煮込みや炙り",
    pairing: "塩、ねぎ、黒胡椒",
    image: "/images/cuts/rosu.png",
  },
];

export const grillGuides = [
  {
    type: "タン",
    title: "強火で短時間、片面に香ばしさを",
    body: "最初の一枚にふさわしく、網がしっかり熱い状態で焼く。返しすぎず、香りが立った瞬間にレモンと塩で。",
  },
  {
    type: "カルビ",
    title: "脂を落としすぎず、焦げすぎは避ける",
    body: "脂が火を呼びやすいので、炎が上がったら網の端へ。表面の焼き目と中の甘い脂を両立させる。",
  },
  {
    type: "赤身",
    title: "中心に少し赤みを残す",
    body: "焼きすぎると硬くなるため、表面を焼いて余熱で仕上げる。塩やわさびで肉の香りを立てる。",
  },
  {
    type: "ヒレ",
    title: "弱めの火で丁寧に",
    body: "繊細な部位なので強い炎に当てすぎない。ゆっくり火を入れ、柔らかさを残して仕上げる。",
  },
  {
    type: "ホルモン",
    title: "皮目からじっくり、脂を香りに変える",
    body: "皮目を下にして弾力を出し、脂を落としながら香ばしく。焦げる前の甘い香りが食べ頃。",
  },
];

export const recipeFilters = ["すべて", "タン", "カルビ", "赤身", "ホルモン", "希少部位"];

export const sharedGrillRecipes = [
  {
    title: "片面香ばしタン塩",
    author: "銀座の網番",
    cut: "タン",
    heat: "強火",
    time: "片面35秒、返して10秒",
    sauce: "塩、レモン、白ねぎ",
    note: "片面をしっかり焼いて香りを出し、裏面は温める程度で止めると歯切れが残ります。",
    steps: ["網の中央をよく熱する", "タンを置いたら動かさず焼き目をつける", "返したら白ねぎをのせてすぐ皿へ"],
    likes: 128,
  },
  {
    title: "中落ちカルビの焦がしだれ焼き",
    author: "炭火係 佐藤",
    cut: "カルビ",
    heat: "中強火",
    time: "表裏45秒ずつ",
    sauce: "甘辛だれ、黒胡椒",
    note: "脂が落ち始めたら火の弱い端へ逃がし、焦げではなく香ばしさで止めるのがコツです。",
    steps: ["最初にたれを薄くまとわせる", "脂が透明になったら一度だけ返す", "仕上げに黒胡椒をひく"],
    likes: 96,
  },
  {
    title: "ランプの余熱ロゼ仕上げ",
    author: "赤身派の夜",
    cut: "赤身",
    heat: "中火",
    time: "表裏40秒、休ませ30秒",
    sauce: "塩、わさび、山椒",
    note: "赤身は焼き台から下ろしたあとも火が入るので、少し早めに休ませると柔らかく仕上がります。",
    steps: ["表面だけを香ばしく焼く", "皿の端で30秒休ませる", "わさびを少量のせて塩で食べる"],
    likes: 143,
  },
  {
    title: "ミノの塩レモン二段焼き",
    author: "酒場の一皿",
    cut: "ホルモン",
    heat: "中火",
    time: "皮目70秒、返して25秒",
    sauce: "塩、レモン、七味",
    note: "最初はじっくり、最後だけ強めに。さくっとした歯切れと香ばしさが両方立ちます。",
    steps: ["切れ目側を下にしてじっくり焼く", "脂と水分が浮いたら返す", "仕上げにレモンを搾る"],
    likes: 87,
  },
  {
    title: "イチボのわさび醤油炙り",
    author: "週末焼肉帖",
    cut: "希少部位",
    heat: "強火",
    time: "片面25秒ずつ",
    sauce: "わさび、薄口醤油",
    note: "サシの甘みを重くしないように、焼きすぎず醤油は香りづけ程度にします。",
    steps: ["網の高温部分で短く焼く", "皿で数秒置いて肉汁を落ち着かせる", "わさびを溶いた薄口醤油を少量つける"],
    likes: 112,
  },
];

export const moodOptions = [
  {
    label: "とにかく満足感がほしい",
    result: "カルビ・中落ちカルビ・ハラミ",
    note: "甘い脂と濃い肉汁で、焼肉らしい高揚感をまっすぐ楽しめます。",
  },
  {
    label: "脂は控えめにしたい",
    result: "ヒレ・ウチモモ・サガリ",
    note: "軽やかな赤身を中心にすると、食後の重さを抑えながら旨味を味わえます。",
  },
  {
    label: "希少部位を楽しみたい",
    result: "イチボ・ミスジ・カイノミ",
    note: "赤身とサシの個性が出やすい部位。塩やわさびで輪郭を整えるのがおすすめです。",
  },
  {
    label: "お酒に合う部位がいい",
    result: "牛タン・ミノ・ホルモン",
    note: "歯切れ、香ばしさ、脂の甘みがあり、ビールや日本酒の余韻に寄り添います。",
  },
  {
    label: "さっぱり食べたい",
    result: "牛タン・ハツ・赤身ロース",
    note: "塩、レモン、ポン酢で軽く。会話をしながらゆっくり楽しむ日に合います。",
  },
];
